### ISSUE TITLE
command not found: electron-installer-dmg

### ISSUE THREAD

**Issue by ytftianwen** [electron-userland/electron-installer-dmg#43]
Platform: macOS Mojave
version: 10.14.4
npm version: 6.12.0
![image](https://user-images.githubusercontent.com/13484089/71353305-935de780-25b3-11ea-95b4-4fb61ae7497b.png)

**Comment by malept** [comment]
How did you install `electron-installer-dmg`?

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in over three months, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
